set search_path = lab_tracker_group_10;

--Upcoming Lab Events--
SELECT sl.SECTION_ID, s.SEC_SET, s.CRS_CODE, l.LAB_TITLE, DATE(sl.SEC_LAB_START) as LAB_EVENT_DATE
FROM SECTION_LAB sl
JOIN SECTION s ON sl.SECTION_ID = s.SECTION_ID
JOIN LAB l ON sl.LAB_ID = l.LAB_ID
WHERE s.TERM_CODE = '202530';

--Student Participation Summary--
SELECT S.USER_ID as STUDENT_ID, COUNT(*) FILTER (WHERE lp.PROG_ATTENDANCE = true) AS TOTAL_LAB_EVENT_ATTENDANCE
FROM student s
JOIN LAB_PROGRESS lp ON lp.STUDENT_ID = s.USER_ID
GROUP BY s.USER_ID;

